name: godoctor MCP server
description: Test the efficacy of the godoctor MCP against the base configuration.
reps: 1
concurrent: 1
timeout: 30m
experiment_control: default
scenarios: []
alternatives:
  - name: default
    description: Base Gemini CLI
    command: gemini
    args:
      - '-y'
      - '-o'
      - stream-json
    settings_blocks: []
    extensions: []
    skills: []
    mcp_servers: []
    settings: {}
  - name: godoctor-mcp
    description: godoctor configured as mcp server
    command: gemini
    args:
      - '-y'
      - '-o'
      - stream-json
    settings_blocks: []
    extensions: []
    skills: []
    mcp_servers:
      - _ui_name: Godoctor
        args: []
        command: godoctor
    settings: {}
  - name: godoctor-extension
    description: godoctor configured via extension
    command: gemini
    args:
      - '-y'
      - '-o'
      - stream-json
    settings_blocks: []
    extensions:
      - _ui_name: Godoctor
        mode: link
        source: /Users/petruzalek/projects/godoctor
    skills: []
    mcp_servers: []
    settings: {}
  - name: godoctor-extension-skills
    description: godoctor configured via extension with skills enabled
    command: gemini
    args:
      - '-y'
      - '-o'
      - stream-json
    settings_blocks:
      - _ui_name: Enable Skills (Experimental)
        experimental.skills: true
    extensions:
      - _ui_name: Godoctor
        mode: link
        source: /Users/petruzalek/projects/godoctor
    skills: []
    mcp_servers: []
    settings: {}
