apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradio-chat-deployment
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: gradio-chat
  template:
    metadata:
      labels:
        app: gradio-chat
    spec:
      containers:
      - name: gradio-chat
        image: chat-app-image
        ports:
        - containerPort: 7860
        imagePullPolicy: Always
        resources:
          requests:
            memory: "150Mi"  # Minimum memory required
            cpu: "10m"       # Minimum CPU shares required
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "100m"       # Maximum CPU shares allowed 
      serviceAccountName: gradio-chat-ksa
---
apiVersion: v1
kind: Service
metadata:
  name: gradio-chat-service
spec:
  selector:
    app: gradio-chat
  ports:
  - protocol: TCP
    port: 7860
    targetPort: 7860
  type: LoadBalancer

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gradio-chat-ksa